#!/bin/bash
# ─────────────────────────────────────────────
#  Deploy Script — Build Vue SPA & sync to Laravel
# ─────────────────────────────────────────────
#  Usage: bash deploy.sh
#  Run from the project root (parent of flash/ and flash-vue/)
# ─────────────────────────────────────────────

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
VUE_DIR="$SCRIPT_DIR/flash-vue"
LARAVEL_DIR="$SCRIPT_DIR/flash"
DEPLOY_TS=$(date +%s)

echo "══════════════════════════════════════════"
echo "  🔨 Building Vue SPA..."
echo "══════════════════════════════════════════"
cd "$VUE_DIR"

# Clean old build output first
rm -rf dist

npm run build

echo ""
echo "══════════════════════════════════════════"
echo "  📦 Syncing build to Laravel public/..."
echo "══════════════════════════════════════════"

# Remove ALL old frontend assets to prevent stale cache
rm -rf "$LARAVEL_DIR/public/assets"
rm -rf "$LARAVEL_DIR/public/build"
cp -r "$VUE_DIR/dist/assets" "$LARAVEL_DIR/public/assets"

# Copy icons & favicon
cp -f "$VUE_DIR/dist/favicon.ico" "$LARAVEL_DIR/public/favicon.ico" 2>/dev/null || true
cp -f "$VUE_DIR/dist/klek-ai-mark.svg" "$LARAVEL_DIR/public/klek-ai-mark.svg" 2>/dev/null || true
cp -f "$VUE_DIR/dist/flash-ai-mark.svg" "$LARAVEL_DIR/public/flash-ai-mark.svg" 2>/dev/null || true

# Copy & stamp the service worker with deploy timestamp to bust SW cache
cp -f "$VUE_DIR/dist/sw.js" "$LARAVEL_DIR/public/sw.js" 2>/dev/null || true
sed -i "s/__DEPLOY_TIMESTAMP__/$DEPLOY_TS/g" "$LARAVEL_DIR/public/sw.js"

# Copy index.html as Blade template
cp -f "$VUE_DIR/dist/index.html" "$LARAVEL_DIR/resources/views/spa.blade.php"

# Prepend Blade comment
TEMP_FILE=$(mktemp)
cat > "$TEMP_FILE" << 'BLADE_COMMENT'
{{-- Auto-generated by deploy.sh — DO NOT edit manually --}}
BLADE_COMMENT
cat "$LARAVEL_DIR/resources/views/spa.blade.php" >> "$TEMP_FILE"
mv "$TEMP_FILE" "$LARAVEL_DIR/resources/views/spa.blade.php"

# Wrap JSON-LD blocks in @verbatim so Blade ignores @context/@type/@graph
SPA_FILE="$LARAVEL_DIR/resources/views/spa.blade.php"
sed -i 's|<script type="application/ld+json">|@verbatim\n    <script type="application/ld+json">|' "$SPA_FILE"
# Find the closing </script> tag right after the ld+json block and add @endverbatim
awk '/@verbatim/{v=1} v && /<\/script>/{print; print "    @endverbatim"; v=0; next} 1' "$SPA_FILE" > "${SPA_FILE}.tmp" && mv "${SPA_FILE}.tmp" "$SPA_FILE"

echo ""
echo "══════════════════════════════════════════"
echo "  🧩 Syncing PHP dependencies..."
echo "══════════════════════════════════════════"
cd "$LARAVEL_DIR"

COMPOSER_INSTALLED_FILE="$LARAVEL_DIR/vendor/composer/installed.php"

if [ ! -f "$LARAVEL_DIR/vendor/autoload.php" ] || [ ! -f "$COMPOSER_INSTALLED_FILE" ] || [ "$LARAVEL_DIR/composer.lock" -nt "$COMPOSER_INSTALLED_FILE" ]; then
	if command -v composer >/dev/null 2>&1; then
		composer install --no-interaction --prefer-dist --optimize-autoloader
	else
		echo "  Composer not found in PATH. Run 'composer install --no-interaction --prefer-dist --optimize-autoloader' before caching Laravel."
	fi
else
	echo "  PHP dependencies are up to date."
fi

echo ""
echo "══════════════════════════════════════════"
echo "  🚀 Optimizing Laravel for production..."
echo "══════════════════════════════════════════"
php artisan optimize:clear
php artisan package:discover --ansi
php artisan config:cache
php artisan route:cache
php artisan view:cache

echo ""
echo "══════════════════════════════════════════"
echo "  ✅ Deploy complete!"
echo "══════════════════════════════════════════"
echo "  Frontend → https://klek.studio/"
echo "  API      → https://klek.studio/api"
echo "══════════════════════════════════════════"
