<?php

namespace Database\Seeders;

use App\Models\Setting;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Crypt;

class SystemSettingsSeeder extends Seeder
{
    public function run(): void
    {
        $settings = [

            // ══════════════════════════════════════════════
            //  API KEYS GROUP
            // ══════════════════════════════════════════════

            [
                'group'        => 'api_keys',
                'key'          => 'openai_api_key',
                'value'        => Crypt::encryptString('sk-demo-key-not-real-1234567890'),
                'type'         => 'string',
                'display_name' => 'OpenAI API Key',
                'description'  => 'Your OpenAI API key for GPT and DALL·E services.',
                'is_public'    => false,
                'is_encrypted' => true,
                'options'      => null,
                'sort_order'   => 1,
            ],
            [
                'group'        => 'api_keys',
                'key'          => 'openai_model',
                'value'        => 'gpt-4',
                'type'         => 'string',
                'display_name' => 'OpenAI Model',
                'description'  => 'Default AI model to use for text generation.',
                'is_public'    => false,
                'is_encrypted' => false,
                'options'      => ['gpt-4', 'gpt-4-turbo', 'gpt-3.5-turbo'],
                'sort_order'   => 2,
            ],
            [
                'group'        => 'api_keys',
                'key'          => 'openai_max_tokens',
                'value'        => '4096',
                'type'         => 'integer',
                'display_name' => 'OpenAI Max Tokens',
                'description'  => 'Maximum tokens per AI request.',
                'is_public'    => false,
                'is_encrypted' => false,
                'options'      => null,
                'sort_order'   => 3,
            ],
            [
                'group'        => 'api_keys',
                'key'          => 'stability_ai_key',
                'value'        => Crypt::encryptString('sk-stab-demo-not-real-9876'),
                'type'         => 'string',
                'display_name' => 'Stability AI Key',
                'description'  => 'API key for Stability AI image generation (Stable Diffusion).',
                'is_public'    => false,
                'is_encrypted' => true,
                'options'      => null,
                'sort_order'   => 4,
            ],
            [
                'group'        => 'api_keys',
                'key'          => 'stability_ai_engine',
                'value'        => 'stable-diffusion-xl-1024-v1-0',
                'type'         => 'string',
                'display_name' => 'Stability AI Engine',
                'description'  => 'Default engine for Stability AI image generation.',
                'is_public'    => false,
                'is_encrypted' => false,
                'options'      => ['stable-diffusion-xl-1024-v1-0', 'stable-diffusion-v1-6', 'stable-diffusion-xl-beta-v2-2-2'],
                'sort_order'   => 5,
            ],
            [
                'group'        => 'api_keys',
                'key'          => 'stripe_public_key',
                'value'        => 'pk_test_demo1234567890',
                'type'         => 'string',
                'display_name' => 'Stripe Public Key',
                'description'  => 'Stripe publishable key (safe for frontend).',
                'is_public'    => true,
                'is_encrypted' => false,
                'options'      => null,
                'sort_order'   => 6,
            ],
            [
                'group'        => 'api_keys',
                'key'          => 'stripe_secret_key',
                'value'        => Crypt::encryptString('sk_test_demo1234567890'),
                'type'         => 'string',
                'display_name' => 'Stripe Secret Key',
                'description'  => 'Stripe secret key for server-side operations.',
                'is_public'    => false,
                'is_encrypted' => true,
                'options'      => null,
                'sort_order'   => 7,
            ],
            [
                'group'        => 'api_keys',
                'key'          => 'stripe_webhook_secret',
                'value'        => Crypt::encryptString('whsec_demo1234567890'),
                'type'         => 'string',
                'display_name' => 'Stripe Webhook Secret',
                'description'  => 'Stripe webhook signing secret for verifying events.',
                'is_public'    => false,
                'is_encrypted' => true,
                'options'      => null,
                'sort_order'   => 8,
            ],
            [
                'group'        => 'api_keys',
                'key'          => 'paypal_client_id',
                'value'        => Crypt::encryptString('AXdemo-paypal-client-id-not-real'),
                'type'         => 'string',
                'display_name' => 'PayPal Client ID',
                'description'  => 'PayPal REST API client ID.',
                'is_public'    => false,
                'is_encrypted' => true,
                'options'      => null,
                'sort_order'   => 9,
            ],
            [
                'group'        => 'api_keys',
                'key'          => 'paypal_client_secret',
                'value'        => Crypt::encryptString('EBdemo-paypal-secret-not-real'),
                'type'         => 'string',
                'display_name' => 'PayPal Client Secret',
                'description'  => 'PayPal REST API client secret.',
                'is_public'    => false,
                'is_encrypted' => true,
                'options'      => null,
                'sort_order'   => 10,
            ],
            [
                'group'        => 'api_keys',
                'key'          => 'paypal_mode',
                'value'        => 'sandbox',
                'type'         => 'string',
                'display_name' => 'PayPal Mode',
                'description'  => 'PayPal environment mode.',
                'is_public'    => false,
                'is_encrypted' => false,
                'options'      => ['sandbox', 'live'],
                'sort_order'   => 11,
            ],

            // ══════════════════════════════════════════════
            //  FEATURES GROUP (toggles)
            // ══════════════════════════════════════════════

            [
                'group'        => 'features',
                'key'          => 'ai_image_generation',
                'value'        => '1',
                'type'         => 'boolean',
                'display_name' => 'AI Image Generation',
                'description'  => 'Enable or disable AI-powered image generation.',
                'is_public'    => true,
                'is_encrypted' => false,
                'options'      => null,
                'sort_order'   => 1,
            ],
            [
                'group'        => 'features',
                'key'          => 'ai_image_editing',
                'value'        => '1',
                'type'         => 'boolean',
                'display_name' => 'AI Image Editing (Inpainting)',
                'description'  => 'Enable or disable AI inpainting / image editing.',
                'is_public'    => true,
                'is_encrypted' => false,
                'options'      => null,
                'sort_order'   => 2,
            ],
            [
                'group'        => 'features',
                'key'          => 'ai_text_generation',
                'value'        => '1',
                'type'         => 'boolean',
                'display_name' => 'AI Text Generation',
                'description'  => 'Enable or disable AI text / content generation.',
                'is_public'    => true,
                'is_encrypted' => false,
                'options'      => null,
                'sort_order'   => 3,
            ],
            [
                'group'        => 'features',
                'key'          => 'user_image_upload',
                'value'        => '1',
                'type'         => 'boolean',
                'display_name' => 'User Image Upload',
                'description'  => 'Allow users to upload their own images.',
                'is_public'    => true,
                'is_encrypted' => false,
                'options'      => null,
                'sort_order'   => 4,
            ],
            [
                'group'        => 'features',
                'key'          => 'paid_subscriptions',
                'value'        => '1',
                'type'         => 'boolean',
                'display_name' => 'Paid Subscriptions',
                'description'  => 'Enable paid subscription plans.',
                'is_public'    => true,
                'is_encrypted' => false,
                'options'      => null,
                'sort_order'   => 5,
            ],
            [
                'group'        => 'features',
                'key'          => 'free_tier_enabled',
                'value'        => '1',
                'type'         => 'boolean',
                'display_name' => 'Free Tier',
                'description'  => 'Enable the free tier for new users.',
                'is_public'    => true,
                'is_encrypted' => false,
                'options'      => null,
                'sort_order'   => 6,
            ],
            [
                'group'        => 'features',
                'key'          => 'registration_enabled',
                'value'        => '1',
                'type'         => 'boolean',
                'display_name' => 'User Registration',
                'description'  => 'Allow new users to register.',
                'is_public'    => true,
                'is_encrypted' => false,
                'options'      => null,
                'sort_order'   => 7,
            ],
            [
                'group'        => 'features',
                'key'          => 'social_login_enabled',
                'value'        => '0',
                'type'         => 'boolean',
                'display_name' => 'Social Login',
                'description'  => 'Enable social login (Google, GitHub, etc.).',
                'is_public'    => true,
                'is_encrypted' => false,
                'options'      => null,
                'sort_order'   => 8,
            ],
            [
                'group'        => 'features',
                'key'          => 'api_access_enabled',
                'value'        => '1',
                'type'         => 'boolean',
                'display_name' => 'API Access',
                'description'  => 'Allow users to access the platform API.',
                'is_public'    => true,
                'is_encrypted' => false,
                'options'      => null,
                'sort_order'   => 9,
            ],

            // ══════════════════════════════════════════════
            //  GENERAL GROUP
            // ══════════════════════════════════════════════

            [
                'group'        => 'general',
                'key'          => 'platform_name',
                'value'        => 'Flash AI',
                'type'         => 'string',
                'display_name' => 'Platform Name',
                'description'  => 'The name of your platform displayed across the site.',
                'is_public'    => true,
                'is_encrypted' => false,
                'options'      => null,
                'sort_order'   => 1,
            ],
            [
                'group'        => 'general',
                'key'          => 'platform_logo',
                'value'        => '/images/logo.png',
                'type'         => 'string',
                'display_name' => 'Platform Logo URL',
                'description'  => 'URL or path to the platform logo.',
                'is_public'    => true,
                'is_encrypted' => false,
                'options'      => null,
                'sort_order'   => 2,
            ],
            [
                'group'        => 'general',
                'key'          => 'platform_favicon',
                'value'        => '/images/favicon.ico',
                'type'         => 'string',
                'display_name' => 'Favicon URL',
                'description'  => 'URL or path to the site favicon.',
                'is_public'    => true,
                'is_encrypted' => false,
                'options'      => null,
                'sort_order'   => 3,
            ],
            [
                'group'        => 'general',
                'key'          => 'theme_mode',
                'value'        => 'dark',
                'type'         => 'string',
                'display_name' => 'Default Theme',
                'description'  => 'Default color theme for the platform.',
                'is_public'    => true,
                'is_encrypted' => false,
                'options'      => ['dark', 'light', 'auto'],
                'sort_order'   => 4,
            ],
            [
                'group'        => 'general',
                'key'          => 'default_language',
                'value'        => 'en',
                'type'         => 'string',
                'display_name' => 'Default Language',
                'description'  => 'Default language for the platform interface.',
                'is_public'    => true,
                'is_encrypted' => false,
                'options'      => ['en', 'ar', 'fr', 'es', 'de'],
                'sort_order'   => 5,
            ],
            [
                'group'        => 'general',
                'key'          => 'timezone',
                'value'        => 'UTC',
                'type'         => 'string',
                'display_name' => 'Timezone',
                'description'  => 'Default timezone for the platform.',
                'is_public'    => true,
                'is_encrypted' => false,
                'options'      => null,
                'sort_order'   => 6,
            ],
            [
                'group'        => 'general',
                'key'          => 'date_format',
                'value'        => 'Y-m-d',
                'type'         => 'string',
                'display_name' => 'Date Format',
                'description'  => 'Default date format for displaying dates.',
                'is_public'    => true,
                'is_encrypted' => false,
                'options'      => ['Y-m-d', 'd/m/Y', 'm/d/Y', 'M d, Y'],
                'sort_order'   => 7,
            ],
            [
                'group'        => 'general',
                'key'          => 'items_per_page',
                'value'        => '15',
                'type'         => 'integer',
                'display_name' => 'Items Per Page',
                'description'  => 'Default pagination size for lists.',
                'is_public'    => true,
                'is_encrypted' => false,
                'options'      => null,
                'sort_order'   => 8,
            ],
            [
                'group'        => 'general',
                'key'          => 'seo_title',
                'value'        => 'Flash AI — AI-Powered Creative Platform',
                'type'         => 'string',
                'display_name' => 'SEO Title',
                'description'  => 'Default page title for search engines.',
                'is_public'    => true,
                'is_encrypted' => false,
                'options'      => null,
                'sort_order'   => 9,
            ],
            [
                'group'        => 'general',
                'key'          => 'seo_description',
                'value'        => 'Generate stunning images and content with cutting-edge AI technology. Transform your creative workflow today.',
                'type'         => 'text',
                'display_name' => 'SEO Description',
                'description'  => 'Default meta description for search engines.',
                'is_public'    => true,
                'is_encrypted' => false,
                'options'      => null,
                'sort_order'   => 10,
            ],
            [
                'group'        => 'general',
                'key'          => 'seo_keywords',
                'value'        => 'AI, image generation, content creation, stable diffusion, GPT, creative tools',
                'type'         => 'text',
                'display_name' => 'SEO Keywords',
                'description'  => 'Default meta keywords for search engines.',
                'is_public'    => true,
                'is_encrypted' => false,
                'options'      => null,
                'sort_order'   => 11,
            ],
            [
                'group'        => 'general',
                'key'          => 'google_analytics_id',
                'value'        => '',
                'type'         => 'string',
                'display_name' => 'Google Analytics ID',
                'description'  => 'Google Analytics tracking ID (e.g. G-XXXXXXXXXX).',
                'is_public'    => true,
                'is_encrypted' => false,
                'options'      => null,
                'sort_order'   => 12,
            ],

            // ══════════════════════════════════════════════
            //  NOTIFICATIONS GROUP
            // ══════════════════════════════════════════════

            [
                'group'        => 'notifications',
                'key'          => 'email_notifications_enabled',
                'value'        => '1',
                'type'         => 'boolean',
                'display_name' => 'Email Notifications',
                'description'  => 'Send notifications via email.',
                'is_public'    => false,
                'is_encrypted' => false,
                'options'      => null,
                'sort_order'   => 1,
            ],
            [
                'group'        => 'notifications',
                'key'          => 'inapp_notifications_enabled',
                'value'        => '1',
                'type'         => 'boolean',
                'display_name' => 'In-App Notifications',
                'description'  => 'Show push-style notifications inside the app.',
                'is_public'    => false,
                'is_encrypted' => false,
                'options'      => null,
                'sort_order'   => 2,
            ],
            [
                'group'        => 'notifications',
                'key'          => 'push_notifications_enabled',
                'value'        => '0',
                'type'         => 'boolean',
                'display_name' => 'Push Notifications',
                'description'  => 'Send browser / mobile push notifications.',
                'is_public'    => false,
                'is_encrypted' => false,
                'options'      => null,
                'sort_order'   => 3,
            ],
            [
                'group'        => 'notifications',
                'key'          => 'sms_notifications_enabled',
                'value'        => '0',
                'type'         => 'boolean',
                'display_name' => 'SMS Notifications',
                'description'  => 'Send notifications via SMS.',
                'is_public'    => false,
                'is_encrypted' => false,
                'options'      => null,
                'sort_order'   => 4,
            ],
            [
                'group'        => 'notifications',
                'key'          => 'notification_from_name',
                'value'        => 'Flash AI',
                'type'         => 'string',
                'display_name' => 'From Name',
                'description'  => 'Sender name for outgoing emails.',
                'is_public'    => false,
                'is_encrypted' => false,
                'options'      => null,
                'sort_order'   => 5,
            ],
            [
                'group'        => 'notifications',
                'key'          => 'notification_from_email',
                'value'        => 'noreply@flash-ai.com',
                'type'         => 'string',
                'display_name' => 'From Email',
                'description'  => 'Sender email address for outgoing emails.',
                'is_public'    => false,
                'is_encrypted' => false,
                'options'      => null,
                'sort_order'   => 6,
            ],
            [
                'group'        => 'notifications',
                'key'          => 'smtp_host',
                'value'        => 'smtp.mailtrap.io',
                'type'         => 'string',
                'display_name' => 'SMTP Host',
                'description'  => 'SMTP server hostname.',
                'is_public'    => false,
                'is_encrypted' => false,
                'options'      => null,
                'sort_order'   => 7,
            ],
            [
                'group'        => 'notifications',
                'key'          => 'smtp_port',
                'value'        => '587',
                'type'         => 'integer',
                'display_name' => 'SMTP Port',
                'description'  => 'SMTP server port.',
                'is_public'    => false,
                'is_encrypted' => false,
                'options'      => null,
                'sort_order'   => 8,
            ],
            [
                'group'        => 'notifications',
                'key'          => 'smtp_username',
                'value'        => Crypt::encryptString('demo_smtp_user'),
                'type'         => 'string',
                'display_name' => 'SMTP Username',
                'description'  => 'SMTP authentication username.',
                'is_public'    => false,
                'is_encrypted' => true,
                'options'      => null,
                'sort_order'   => 9,
            ],
            [
                'group'        => 'notifications',
                'key'          => 'smtp_password',
                'value'        => Crypt::encryptString('demo_smtp_pass'),
                'type'         => 'string',
                'display_name' => 'SMTP Password',
                'description'  => 'SMTP authentication password.',
                'is_public'    => false,
                'is_encrypted' => true,
                'options'      => null,
                'sort_order'   => 10,
            ],
            [
                'group'        => 'notifications',
                'key'          => 'smtp_encryption',
                'value'        => 'tls',
                'type'         => 'string',
                'display_name' => 'SMTP Encryption',
                'description'  => 'SMTP encryption method.',
                'is_public'    => false,
                'is_encrypted' => false,
                'options'      => ['tls', 'ssl', 'none'],
                'sort_order'   => 11,
            ],
            [
                'group'        => 'notifications',
                'key'          => 'mailgun_domain',
                'value'        => '',
                'type'         => 'string',
                'display_name' => 'Mailgun Domain',
                'description'  => 'Domain configured in Mailgun.',
                'is_public'    => false,
                'is_encrypted' => false,
                'options'      => null,
                'sort_order'   => 12,
            ],
            [
                'group'        => 'notifications',
                'key'          => 'mailgun_secret',
                'value'        => Crypt::encryptString(''),
                'type'         => 'string',
                'display_name' => 'Mailgun API Secret',
                'description'  => 'Mailgun API secret key.',
                'is_public'    => false,
                'is_encrypted' => true,
                'options'      => null,
                'sort_order'   => 13,
            ],

            // ══════════════════════════════════════════════
            //  MAINTENANCE GROUP
            // ══════════════════════════════════════════════

            [
                'group'        => 'maintenance',
                'key'          => 'maintenance_mode',
                'value'        => '0',
                'type'         => 'boolean',
                'display_name' => 'Maintenance Mode',
                'description'  => 'When enabled, only admins can access the platform.',
                'is_public'    => true,
                'is_encrypted' => false,
                'options'      => null,
                'sort_order'   => 1,
            ],
            [
                'group'        => 'maintenance',
                'key'          => 'maintenance_message',
                'value'        => 'The platform is currently under maintenance. We will be back shortly. Thank you for your patience.',
                'type'         => 'text',
                'display_name' => 'Maintenance Message',
                'description'  => 'Message displayed to users during maintenance.',
                'is_public'    => true,
                'is_encrypted' => false,
                'options'      => null,
                'sort_order'   => 2,
            ],
            [
                'group'        => 'maintenance',
                'key'          => 'maintenance_allowed_ips',
                'value'        => '[]',
                'type'         => 'json',
                'display_name' => 'Allowed IPs During Maintenance',
                'description'  => 'JSON array of IP addresses that can bypass maintenance mode.',
                'is_public'    => false,
                'is_encrypted' => false,
                'options'      => null,
                'sort_order'   => 3,
            ],
        ];

        foreach ($settings as $data) {
            Setting::updateOrCreate(
                ['key' => $data['key']],
                $data
            );
        }

        Setting::clearCache();

        $this->command->info('SystemSettingsSeeder: ' . count($settings) . ' settings seeded across 5 groups.');
    }
}
